# Generated by Django 3.2.8 on 2024-12-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=255, unique=True)),
                ('contagem', models.IntegerField(default=0)),
            ],
        ),
    ]
